# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-01 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20160901_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetwork',
            name='network_id',
            field=models.IntegerField(blank=True, choices=[(0, 'VK'), (1, 'Facebook'), (2, 'Pinterest'), (3, 'Twitter'), (5, 'Odnoklassniki')], null=True, unique=True, verbose_name='Network ID'),
        ),
    ]
