# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-31 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20160904_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.IntegerField(choices=[(0, 'Offline'), (1, 'Online')], default=0, verbose_name='User online status'),
        ),
    ]
